#!/bin/sh

ONESHOTS_FILE=/var/cache/core-dumps/oneshots

IFS=$'\n'

# Find all files and file symlinks in current users oneshot directory.
USERID=$(loginctl list-sessions | grep seat0 | tr -s " " | cut -d " " -f 3)
ONESHOTS="$(find -L $(find /etc/oneshot.d/$USERID -type d) -maxdepth 1 -type f)"

PREVIOUS_ONESHOTS="$(cat $ONESHOTS_FILE 2>/dev/null)"

echo "$ONESHOTS" | while read oneshot; do
	is_new=0
	echo "$PREVIOUS_ONESHOTS" | while read oldshot; do
		if [ "$oneshot" = "$oldshot" ]; then
			is_new=1
			break
		fi
	done
	if [ $is_new -eq 0 ]; then
		logger "Found failed oneshot script; dumping log files."
		echo "${ONESHOTS}" > "$ONESHOTS_FILE"
		/usr/sbin/rich-core-dumper --name=OneshotFailure --signal=$RANDOM
		break
	fi
done
